# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "virtio_pci" "virtio_scsi" "xhci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7cd88e82-5e45-4791-b3a7-5a4a68da4172";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."crypto".device = "/dev/disk/by-uuid/1f15f2ec-a16b-4217-ab08-cb96e53ac865";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8080c616-d1e1-497a-9a72-bc8450089cd8";
      fsType = "ext2";
    };

  swapDevices = [ ];

}
